server:
  port: 8081
  compression:
    enabled: true
  tomcat:
    max-http-form-post-size: -1
  servlet:
    context-path: /
  shutdown: GRACEFUL
  error:
    include-message: ALWAYS
    include-exception: true



#management:
#  endpoint:
#    health:
#      show-details: always
#    shutdown:
#      enabled: true

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'   # 测试使用，线上不要用*，按需开启


spring:

  profiles:
    active: dev,hippo4j
  lifecycle:
    timeout-per-shutdown-phase: 10s
  web:
    locale: zh
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true


  datasource:
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 15
      # 最大连接数
      max-active: 300
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
      test-while-idle: true
      # 指明是否在从池中取出连接前进行检验,如果检验失败, 则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      # 是否在归还到池中前进行检验
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        allow:
        enabled: true
        # 控制台管理用户名和密码
        url-pattern: /druid/*
        reset-enable: false
        login-username: ENC(uk69Pk7gMcucnPDIOiSnNw==)
        login-password: ENC(KbRnPQSTmSYV45tfR0LtkGvMxMnVoPnp)
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 500
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true